### ISSUE TITLE
List Configs Don't Work When Using Environment Variables

### ISSUE THREAD

**Issue by TheConnMan** [randsleadershipslack/destalinator#167]
Using a config like `ignore_channel_patterns` through the environment variable `DESTALINATOR_IGNORE_CHANNEL_PATTERNS=^auto-` causes everything to be ignored. The string pattern is not casted into a list properly and causes unexpected behavior. If there's a better env var syntax for this to work out of the box we should update docs, otherwise we'll need to code in a solution or not support env vars for list properties.

**Comment by kmarekspartz** [comment]
I think the workaround for this was to add a comma at the end, so it “splits” into a list of one. Not a great syntax...

–
Kyle Marek-Spartz

**Comment by TheConnMan** [comment]
If it works it works. I'll test it and (assuming it works) update the docs.
