### ISSUE TITLE
404 for pre-built Docker image

### ISSUE THREAD

**Issue by astrostl** [randsleadershipslack/destalinator#170]
https://hub.docker.com/r/randsleadershipslack/destalinator/ returns a 404.

**Comment by kmarekspartz** [comment]
Thanks! The link was added by @TheConnMan in advance of someone putting an image there. I don't think anyone has gotten around to that.  @TheConnMan may have the image namespaced elsewhere, but otherwise this is duplicate of #139.

**Comment by TheConnMan** [comment]
No, I don't have an up to date image anywhere else.
