### ISSUE TITLE
permission/scope issue

### ISSUE THREAD

**Issue by choiridge** [randsleadershipslack/destalinator#185]
Hi, I'm building something similar and stumbled upon destalinator on the internet. I'm currently having some issues with getting `last_read` value in `channels.info`'s json response for channels I'm not a member of. Wonder if you have some experience dealing with that. Any insights you could share? Thanks!

**Comment by kmarekspartz** [comment]
I don't see us using last_read anywhere in this repository. We might be using an older API version, not sure.
