### ISSUE TITLE
Missing files in master (archiver.py and warner.py)

### ISSUE THREAD

**Issue by bjmccotter7192** [randsleadershipslack/destalinator#221]
Hi there, I was attempting to use this slack bot to clean up some old channels in our organization but it seems that the two main files don't exist anymore in master?

Is this actively being maintained and if so are there plans to add the default functionality back to the master branch?

Thanks!

**Comment by kmarekspartz** [comment]
The original Slack this was written for was running into Slack API bugs for over a year and no one took the time to fully debug it to get it running again. It moved to using https://www.happybara.io/apps/channitor/ for the warn/archive functionality which works but has an odd UX around snoozing. The remaining functionality from this repo is the announcer which is working mostly fine (some race condition bugs there but not typically noticed).

That said, it is also running on a Heroku free plan which will be turning off soon...

If you need the warner/archiver I would suggest forking and using a commit from before they were removed.

**Comment by bjmccotter7192** [comment]
Alright sounds good thanks so much for the response!
