### ISSUE TITLE
Proposal: member matching based on tags

### ISSUE THREAD

**Issue by sheeley** [randsleadershipslack/destalinator#38]
## Overview
I saw this interaction happen in #intros and thought it was wonderful.
> user1
> ... some introduction, including details of job ...
> thanks :simple_smile:
> 
> user2
> Also, BTW, you and @user3 are both basically doing the same thing, so you might enjoy chatting.

Adding a feature where users can tag themselves could potentially improve onboarding and cross-pollination of existing users. 

## Interface Draft Suggestion
> slackbot
> hi! welcome to rands-leadership. as part of our member matching, we'd love you to tag yourself (using terms like ecommerce, founder, etc.) to help match you with other users. for more information, type `@randsbot matcher help`. 
> 
> @randsbot matcher help
>
> slackbot
> Hi @sheeley, the matcher command is used to help connect you to users who are interested in discussing similar topics. Try these commands:
> * list - list all current tags
> * add [ecommerce, founders, tag3, ...] - associate yourself with certain tags
> * remove [ecommerce, tag2, ...] - remove association with tags
> * match - show a random match with similar interests
> * channel [tag] - create a channel and invite people tagged with [tag]

This is just spitballing, and full credit is due to @royrapoport. I'd love to see suggestions/changes, and happy to help implement once the draft is solidified (if the community feels this would be worthwhile).

**Comment by zeckalpha** [comment]
We likely don't need tags as we have channel membership and participation, as well as word usage.

**Comment by sheeley** [comment]
@zeckalpha I may not be explaining well, my intention is to provide a more obvious method of saying "I am into subject `x`" in a format that is less ephemeral than a typical slack message, so anyone else can say "Ah, man, I wish I knew someone on here who knows about `x`", rather than just posting that question in #general or #help-and-advice.

Are you suggesting that this itself is unecessary, or just that there's a different solution?

**Comment by zeckalpha** [comment]
There's a few other solutions, and a few different problems ;) . If you're looking to suggest people to chat with based on interests, I think channel membership and word usage can go a long way, without having to create a new thing: tags.

For the described problem: Slack's builtin search is good. We could use search e.g. `in:#interests ecommerce`.

**Comment by mnewkirk** [comment]
@zeckalpha To clarify, are you suggesting that people mention their interests in an #interests metadata channel instead of in metadata that's hosted elsewhere?

**Comment by zeckalpha** [comment]
Yes. That would be a no code solution to do what @sheeley is describing.

**Comment by sheeley** [comment]
I like no-code ideas. :)

**Comment by zeckalpha** [comment]
Created room: https://rands-leadership.slack.com/archives/interests

**Comment by sheeley** [comment]
^ :+1:
