### ISSUE TITLE
#zmeta_flagged should pick up aliases for :save:

### ISSUE THREAD

**Issue by daveoflynn** [randsleadershipslack/destalinator#59]
The 💾  icon has two aliases:
:save :
:floppy_disk : 
_(spaces deliberately added to avoid rendering emoji)_

If the first person to wish to save a message uses the floppy form, others will also click on this and the message will never be picked up and put into #zmeta_flagged.

You can see this effect here:
https://rands-leadership.slack.com/archives/help-and-advice/p1471971278002815

**Comment by daveoflynn** [comment]
Fixed as part of #60

**Comment by daveoflynn** [comment]
This comment had the floppy_disk and wasn't echoed to #zmeta_flagged:
https://rands-leadership.slack.com/archives/help-and-advice/p1475078658002226

**Comment by zeckalpha** [comment]
I'm presently seeing these going to #zmeta-flagged. I suspect if any are being missed it is due to crashing rather than due to missing the aliases at this point. Feel free to reopen.
