### ISSUE TITLE
floppy_disk emoji warning

### ISSUE THREAD

**Issue by fromonesrc** [randsleadershipslack/destalinator#72]
I'm seeing this warning even though the 💾 emoji _does_ exist for my Slack team. I've even set it as a reaction to a Slack message just in case that was why it was complaining, but it persists:

`WARNING: Flagger attempted to use an emoji that does not exist. Please add the floppy_disk emoji.`

**Comment by dlovitch** [comment]
@fromonesrc I believe commit 600fd0980becafecd613956d7d8d73d8d6d0708c should fix this issue.

**Comment by fromonesrc** [comment]
It does! ❤️
