### ISSUE TITLE
hitting rate limit

### ISSUE THREAD

**Issue by BrianHicks** [randsleadershipslack/destalinator#89]
I'm testing out destalinator on our Slack, and it hits the rate limit immediately. Is this a known issue? Is it because I'm using a personal access token, as recommended in the README?

Edit: here's the log output:

```
Destalinating
destalinator_activated is False
output_debug_to_slack_flag is True
destalinator_activated is False
destalinator_activated is False
ERROR:apscheduler.executors.default:Job "destalinate_job (trigger: cron[hour='*', minute='*/1'], next run at: 2017-04-19 21:01:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/apscheduler/executors/base.py", line 112, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "scheduler.py", line 20, in destalinate_job
    scheduled_archiver = archiver.Archiver()
  File "/app/executor.py", line 27, in __init__
    self.slacker = slacker.Slacker(config.SLACK_NAME, token=api_token)
  File "/app/slacker.py", line 20, in __init__
    self.get_users()
  File "/app/slacker.py", line 36, in get_users
    payload = requests.get(url).json()['members']
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/app/.heroku/python/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/app/.heroku/python/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/app/.heroku/python/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

It does correctly say that I'm running it every minute, but this happens even if I wait a long time between invocations. It hasn't successfully run to repeat yet.

**Comment by zeckalpha** [comment]
I know it is separate from the rate limit issue, but you shouldn't need to run it minutely. Most instances run once every 24 hours.

I would suspect that the same token is being used by another integration. Can you provision a new token _just_ for the destalinator and try again?

**Comment by BrianHicks** [comment]
Yep! It was running into the rate limit *in the first run*, so the cron schedule didn't really come into account.

The token wasn't being used by any other integrations. It was a fresh personal token. I ended up creating a new app and figuring out the permissions. If it's helpful, here's the minimum set that destalinator needs right now:

![minimum set of permissions for destalinator](https://cloud.githubusercontent.com/assets/355401/25243381/77703256-25c2-11e7-9e7d-9d801624f909.png)

That solved it.

**Comment by zeckalpha** [comment]
Awesome. If you'd like, can you add those permissions to the README? I'm going to close out this issue.
